
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Programm/msys2/mingw64/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/3.27.8/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i"
      binary: "D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i'
        
        Run Build Command(s): "D:/Programm/CLion 2023.3.3/bin/ninja/win/x64/ninja.exe" -v cmTC_9d6ac
        [1/2] D:\\Programm\\msys2\\mingw64\\bin\\clang.exe   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_9d6ac.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -c "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c"
        clang version 19.1.7
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: D:/Programm/msys2/mingw64/bin
         (in-process)
         "D:/Programm/msys2/mingw64/bin/clang.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-sized-deallocation -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i -v -fcoverage-compilation-dir=D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i -resource-dir D:/Programm/msys2/mingw64/lib/clang/19 -dependency-file "CMakeFiles\\\\cmTC_9d6ac.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem D:/Programm/msys2/mingw64/lib/clang/19/include -internal-isystem D:/Programm/msys2/mingw64/x86_64-w64-mingw32/include -internal-isystem D:/Programm/msys2/mingw64/x86_64-w64-mingw32/usr/include -internal-isystem D:/Programm/msys2/mingw64/include -ferror-limit 19 -femulated-tls -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -faddrsig -o CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -x c "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c"
        clang -cc1 version 19.1.7 based upon LLVM 19.1.7 default target x86_64-w64-windows-gnu
        ignoring nonexistent directory "D:/Programm/msys2/mingw64/x86_64-w64-mingw32/include"
        ignoring nonexistent directory "D:/Programm/msys2/mingw64/x86_64-w64-mingw32/usr/include"
        #include "..." search starts here:
        #include <...> search starts here:
         D:/Programm/msys2/mingw64/lib/clang/19/include
         D:/Programm/msys2/mingw64/include
        End of search list.
        [2/2] cmd.exe /C "cd . && D:\\Programm\\msys2\\mingw64\\bin\\clang.exe  -v CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -o cmTC_9d6ac.exe -Wl,--out-implib,libcmTC_9d6ac.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
        clang version 19.1.7
        Target: x86_64-w64-windows-gnu
        Thread model: posix
        InstalledDir: D:/Programm/msys2/mingw64/bin
         "D:/Programm/msys2/mingw64/bin/ld" -m i386pep -Bdynamic -o cmTC_9d6ac.exe D:/Programm/msys2/mingw64/lib/crt2.o D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o -LD:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0 -LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib -LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib -LD:/Programm/msys2/mingw64/lib -LD:/Programm/msys2/mingw64/lib/clang/19/lib/windows CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_9d6ac.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [D:/Programm/msys2/mingw64/lib/clang/19/include]
          add: [D:/Programm/msys2/mingw64/include]
        end of search list found
        collapse include dir [D:/Programm/msys2/mingw64/lib/clang/19/include] ==> [D:/Programm/msys2/mingw64/lib/clang/19/include]
        collapse include dir [D:/Programm/msys2/mingw64/include] ==> [D:/Programm/msys2/mingw64/include]
        implicit include dirs: [D:/Programm/msys2/mingw64/lib/clang/19/include;D:/Programm/msys2/mingw64/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:152 (message)"
      - "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld\\.lld\\.exe|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: 'D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i']
        ignore line: []
        ignore line: [Run Build Command(s): "D:/Programm/CLion 2023.3.3/bin/ninja/win/x64/ninja.exe" -v cmTC_9d6ac]
        ignore line: [[1/2] D:\\Programm\\msys2\\mingw64\\bin\\clang.exe   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_9d6ac.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -c "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c"]
        ignore line: [clang version 19.1.7]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: D:/Programm/msys2/mingw64/bin]
        ignore line: [ (in-process)]
        ignore line: [ "D:/Programm/msys2/mingw64/bin/clang.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-sized-deallocation -fno-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i -v -fcoverage-compilation-dir=D:/ITMO/interview/Repos/C-PP-ITMO/C/lab1/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0gdd9i -resource-dir D:/Programm/msys2/mingw64/lib/clang/19 -dependency-file "CMakeFiles\\\\cmTC_9d6ac.dir\\\\CMakeCCompilerABI.c.obj.d" -MT CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -sys-header-deps -internal-isystem D:/Programm/msys2/mingw64/lib/clang/19/include -internal-isystem D:/Programm/msys2/mingw64/x86_64-w64-mingw32/include -internal-isystem D:/Programm/msys2/mingw64/x86_64-w64-mingw32/usr/include -internal-isystem D:/Programm/msys2/mingw64/include -ferror-limit 19 -femulated-tls -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -exception-model=seh -fcolor-diagnostics -faddrsig -o CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -x c "D:/Programm/CLion 2023.3.3/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeCCompilerABI.c"]
        ignore line: [clang -cc1 version 19.1.7 based upon LLVM 19.1.7 default target x86_64-w64-windows-gnu]
        ignore line: [ignoring nonexistent directory "D:/Programm/msys2/mingw64/x86_64-w64-mingw32/include"]
        ignore line: [ignoring nonexistent directory "D:/Programm/msys2/mingw64/x86_64-w64-mingw32/usr/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ D:/Programm/msys2/mingw64/lib/clang/19/include]
        ignore line: [ D:/Programm/msys2/mingw64/include]
        ignore line: [End of search list.]
        ignore line: [[2/2] cmd.exe /C "cd . && D:\\Programm\\msys2\\mingw64\\bin\\clang.exe  -v CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj -o cmTC_9d6ac.exe -Wl --out-implib libcmTC_9d6ac.dll.a -Wl --major-image-version 0 --minor-image-version 0   && cd ."]
        ignore line: [clang version 19.1.7]
        ignore line: [Target: x86_64-w64-windows-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: D:/Programm/msys2/mingw64/bin]
        link line: [ "D:/Programm/msys2/mingw64/bin/ld" -m i386pep -Bdynamic -o cmTC_9d6ac.exe D:/Programm/msys2/mingw64/lib/crt2.o D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o -LD:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0 -LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib -LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib -LD:/Programm/msys2/mingw64/lib -LD:/Programm/msys2/mingw64/lib/clang/19/lib/windows CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_9d6ac.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o]
          arg [D:/Programm/msys2/mingw64/bin/ld] ==> ignore
          arg [-m] ==> ignore
          arg [i386pep] ==> ignore
          arg [-Bdynamic] ==> search dynamic
          arg [-o] ==> ignore
          arg [cmTC_9d6ac.exe] ==> ignore
          arg [D:/Programm/msys2/mingw64/lib/crt2.o] ==> obj [D:/Programm/msys2/mingw64/lib/crt2.o]
          arg [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o] ==> obj [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o]
          arg [-LD:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0] ==> dir [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0]
          arg [-LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib] ==> dir [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib]
          arg [-LD:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib] ==> dir [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib]
          arg [-LD:/Programm/msys2/mingw64/lib] ==> dir [D:/Programm/msys2/mingw64/lib]
          arg [-LD:/Programm/msys2/mingw64/lib/clang/19/lib/windows] ==> dir [D:/Programm/msys2/mingw64/lib/clang/19/lib/windows]
          arg [CMakeFiles/cmTC_9d6ac.dir/CMakeCCompilerABI.c.obj] ==> ignore
          arg [--out-implib] ==> ignore
          arg [libcmTC_9d6ac.dll.a] ==> ignore
          arg [--major-image-version] ==> ignore
          arg [0] ==> ignore
          arg [--minor-image-version] ==> ignore
          arg [0] ==> ignore
          arg [-lmingw32] ==> lib [mingw32]
          arg [-lgcc] ==> lib [gcc]
          arg [-lgcc_eh] ==> lib [gcc_eh]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-lpthread] ==> lib [pthread]
          arg [-ladvapi32] ==> lib [advapi32]
          arg [-lshell32] ==> lib [shell32]
          arg [-luser32] ==> lib [user32]
          arg [-lkernel32] ==> lib [kernel32]
          arg [-lmingw32] ==> lib [mingw32]
          arg [-lgcc] ==> lib [gcc]
          arg [-lgcc_eh] ==> lib [gcc_eh]
          arg [-lmoldname] ==> lib [moldname]
          arg [-lmingwex] ==> lib [mingwex]
          arg [-lmsvcrt] ==> lib [msvcrt]
          arg [-lkernel32] ==> lib [kernel32]
          arg [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o] ==> obj [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o]
        remove lib [gcc_eh]
        remove lib [msvcrt]
        remove lib [gcc_eh]
        remove lib [msvcrt]
        collapse library dir [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0] ==> [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0]
        collapse library dir [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib] ==> [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib]
        collapse library dir [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib] ==> [D:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib]
        collapse library dir [D:/Programm/msys2/mingw64/lib] ==> [D:/Programm/msys2/mingw64/lib]
        collapse library dir [D:/Programm/msys2/mingw64/lib/clang/19/lib/windows] ==> [D:/Programm/msys2/mingw64/lib/clang/19/lib/windows]
        implicit libs: [mingw32;gcc;moldname;mingwex;pthread;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex;kernel32]
        implicit objs: [D:/Programm/msys2/mingw64/lib/crt2.o;D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtbegin.o;D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/crtend.o]
        implicit dirs: [D:/Programm/msys2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0;D:/Programm/msys2/mingw64/x86_64-w64-mingw32/lib;D:/Programm/msys2/mingw64/x86_64-w64-mingw32/mingw/lib;D:/Programm/msys2/mingw64/lib;D:/Programm/msys2/mingw64/lib/clang/19/lib/windows]
        implicit fwks: []
      
      
...
